CREATE TABLE configs (
	id UUID PRIMARY KEY,
	key VARCHAR(60) NOT NULL UNIQUE,
	value JSONB,
	created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
	updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);
CREATE INDEX idx_configs_key ON configs(key);
