CREATE TABLE kv (
	id UUID PRIMARY KEY,
	key VARCHAR(64) NOT NULL UNIQUE,
	value TEXT NOT NULL,
	expires_at TIMESTAMP,
	created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
	updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);
CREATE INDEX idx_kv_expires_at ON kv(expires_at);
