CREATE TABLE async_tasks_meta (
	id UUID PRIMARY KEY,
	async_task_id UUID NOT NULL REFERENCES async_tasks(id) ON DELETE CASCADE,
	key VARCHAR(60) NOT NULL,
	value JSONB,
	created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
	updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
	UNIQUE (async_task_id, key)
);
