CREATE TABLE workspaces (
	id UUID PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
	handle VARCHAR(100) NOT NULL UNIQUE,
	meta JSONB,
	created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
	updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);
CREATE INDEX idx_workspaces_handle ON workspaces(handle);
