CREATE TABLE user_sessions (
	id UUID PRIMARY KEY,
	token VARCHAR(100) NOT NULL UNIQUE,
	user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	ip_address VARCHAR(45),
	user_agent VARCHAR(200),
	expires_at TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
	updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);
CREATE INDEX idx_user_sessions_token ON user_sessions(token);
